Add persistent option for ACME nonces
dogtagpki/pki pull request #3436
Opened 2021-01-15 20:20 UTC by edewata

Previously ACME nonces were stored in ACME database, which
could generate a lot of database traffic and might not work
well in clustered environment due to replication latency.

To address the performance issue, the ACME database has been
modified to store the nonces in memory by default, and provide
an option to store the nonces in the database if necessary.

The replication latency issue should be addressed using other
mechanisms (e.g. using static base URL in ACME directory).

2021-01-18 01:25 UTC, frasertweedale requested changes
@edewata I think the approach is not correct.  The fact that the `LDAPDatabase` is deferring part of its implementation to another class (the superclass) based on a boolean config is not ideal.

Instead, I think the choice between local nonce cache or database nonce storage should be made in `ACMEEngine.createNonce()/.validateNonce()`.  The cache object should also be initialised there.  Dispatch either to the local cache or the database based on the `nonce.persistent` setting (which can be in `engine.conf`).  Then there are no changes to database classes needed at all, and it does not mix the separate concerns of service configuration and database storage behaviour.

This should be a straightforward change.

2021-01-18 20:19 UTC, edewata commented
Thanks for the feedback. I've updated the patch, rebased it on top of PR #3435, and updated the build as well.

2021-01-19 06:17 UTC, frasertweedale commented
@edewata thanks, I approve the new implementation!

2021-01-19 07:26 UTC, frasertweedale commented
@edewata I'm happy for this change to merged *separately from* #3435.  I think much more [testing](https://github.com/dogtagpki/pki/pull/3435#issuecomment-762654261) must be done to verify that the "pin via registry" approach to ACME load balancing and with server affinity is valid across the full range of ACME scenarios, including renewal and revocation.

2021-01-19 22:26 UTC, edewata commented
I've rebased this PR against master branch, so this is ready to merge.

2021-01-19 23:38 UTC, merged