AuthorityService.getCert/Chain: avoid NPE if CA is not ready
dogtagpki/pki pull request #3605
Opened 2021-06-28 15:10 UTC by ckelleyRH

Fixed backported commit, original commit message follows:

--
If a LWCA is not ready (i.e. key replication and signing unit
initialisation has not completed), asking for its certificate (or
chain) results in a NullPointerException.  Update
AuthorityService.getCert() and .getChain() to raise
ResourceNotFoundException instead.

Part of: https://pagure.io/dogtagpki/issue/3102

2021-06-28 15:12 UTC, ckelleyRH commented
I have provisioned a RHEL7 VM, cloned the code and pulled dependencies for 10.5. I cherry-picked @frasertweedale's original commit and made his suggested corrections and with a bit of further massaging it now builds from source.

2021-06-28 23:01 UTC, frasertweedale requested changes
I think there's a mistake in the `getCert` method, where the not-found check is executed against the chain, not the certificate.

2021-07-28 11:26 UTC, ckelleyRH commented on base/ca/src/org/dogtagpki/server/ca/rest/AuthorityService.java
> +
@frasertweedale I'm sorry it took so long to circle back to this, and that I'm making this look very complicated! I think I may have taken a suggestion you made in an email too literally, I have made a new patch.

2021-07-28 13:34 UTC, frasertweedale reviewed
OK, this LGTM now.  I leave final ACK to others after it has been tested.

2021-07-29 14:31 UTC, ckelleyRH commented
@frasertweedale how would you test this? The first time we just merged it in because "it works on RHEL8", and we only reverted it because it prevented compilation. Now I know it won't break the build, and you're happy that it looks OK, I was going to merge it in again and let QE do their thing. There are no steps to reproduce in the BZ and it looks like the customer was running this via IPA, so it is beyond my current limited knowledge to reproduce without some help.

2021-07-30 00:39 UTC, frasertweedale commented
I would propose something like:
1. deploy dogtag
2. create a lightweight CA (LWCA)
3. stop Dogtag
4. in the NSSDB, delete the certificate and key for the lightweight CA
5. restart Dogtag
6. perform REST requests for the lightweight CA's cert and chain.  They should not result in 500.

It's OK to let QE handle it, but maybe it is worth going through the steps. You will learn a bit more about how LWCAs function.
If you want to walk through it together, we can meet to do that.

2021-07-30 09:14 UTC, ckelleyRH commented
I think I will merge to allow QE time to do what they need to do for the next batch update, but I have emailed you to take you up on your offer of a walkthrough - thanks! There is a big ecosystem of inter-related products to learn and any and all help is most welcome.

2021-07-30 09:14 UTC, merged