Drop SHA-1 fingerprints
dogtagpki/pki pull request #3824
Opened 2021-11-05 22:06 UTC by edewata

2022-04-13 15:05 UTC, ckelleyRH requested changes
I think the time has come to un-defer this.

There are a few places where I think renewed examples in the javadoc would help.

Also, can we lose `MD2` and `MD5` at the same time and maybe add in `SHA-384` fingerprints? I don't know what the consequences of doing this in the C code are. Are they conforming to some external expectations for algorithms or can we drop `MD2`/`MD5`; add `SHA-384` there too?

2022-04-13 15:05 UTC, ckelleyRH commented on base/server/src/main/java/com/netscape/cmscore/cert/CertUtils.java
> +     * MD5 and MD2 hashes.
Drop `MD2`/`MD5`, add `SHA-256`, `SHA-384` and `SHA-512`?

2022-04-13 15:05 UTC, ckelleyRH commented on base/server/src/main/java/com/netscape/cmscore/cert/CertUtils.java
> +        String[] hashes = new String[] { "MD2", "MD5", "SHA256", "SHA512" };
Drop `MD2`/`MD5`, add `SHA-256`, `SHA-384` and `SHA-512`?

2022-04-13 15:08 UTC, ckelleyRH commented
I started commenting on individual lines before I realised that I could probably just summarise in a few lines, there are still some "unmarked" places where I didn't leave comments.

2022-04-13 15:11 UTC, edewata commented
@ckelleyRH Thanks for your comments!
@ladycfu Do you have any objections about this PR and the suggested changes?

2022-07-08 15:59 UTC, edewata commented
I'd have to defer to @ladycfu.

2023-03-15 14:12 UTC, ckelleyRH commented
@edewata shall we close this?

2023-03-15 16:00 UTC, edewata commented
Let's check with @ladycfu.

2025-04-03 02:46 UTC, closed without merging